### ISSUE TITLE
【HotFix】本の登録に失敗する

### ISSUE THREAD

**Issue by kumackey** [kumackey/book-output#131]
失敗した本

実践Rails

I, [2020-05-10T13:58:32.955845 #20106]  INFO -- : [3438910f-6452-4dd7-9146-6be0db25e31d] Started POST "/books?googlebooksapi_id=-7iMOLUQDqQC" for 111.239.252.130 at 2020-05-10 13:58:32 +0000
I, [2020-05-10T13:58:32.956531 #20106]  INFO -- : [3438910f-6452-4dd7-9146-6be0db25e31d] Processing by BooksController#create as HTML
I, [2020-05-10T13:58:32.956586 #20106]  INFO -- : [3438910f-6452-4dd7-9146-6be0db25e31d]   Parameters: {"authenticity_token"=>"XomQBbiRRSgaoIaI/O3mZizBAPtraTJaKy6/3/l6nqx5EnelKqm7rCcYcAl5myhqOIf4/1KIAjNFjyPwE2O6HA==", "googlebooksapi_id"=>"-7iMOLUQDqQC"}
D, [2020-05-10T13:58:33.344364 #20106] DEBUG -- : [3438910f-6452-4dd7-9146-6be0db25e31d]   ESC[1mESC[36mBook Load (0.6ms)ESC[0m  ESC[1mESC[34mSELECT  `books`.* FROM `books` WHERE `books`.`googlebooksapi_id` = '-7iMOLUQDqQC' LIMIT 1ESC[0m
D, [2020-05-10T13:58:33.345814 #20106] DEBUG -- : [3438910f-6452-4dd7-9146-6be0db25e31d]   ESC[1mESC[36mBook Exists (0.5ms)ESC[0m  ESC[1mESC[34mSELECT  1 AS one FROM `books` WHERE `books`.`googlebooksapi_id` = '-7iMOLUQDqQC' LIMIT 1ESC[0m
D, [2020-05-10T13:58:33.346352 #20106] DEBUG -- : [3438910f-6452-4dd7-9146-6be0db25e31d]   ESC[1mESC[35m (0.4ms)ESC[0m  ESC[1mESC[35mBEGINESC[0m
D, [2020-05-10T13:58:33.561634 #20106] DEBUG -- : [3438910f-6452-4dd7-9146-6be0db25e31d]   ESC[1mESC[36mCACHE Book Exists (0.0ms)ESC[0m  ESC[1mESC[34mSELECT  1 AS one FROM `books` WHERE `books`.`googlebooksapi_id` = '-7iMOLUQDqQC' LIMIT 1ESC[0m
D, [2020-05-10T13:58:33.563389 #20106] DEBUG -- : [3438910f-6452-4dd7-9146-6be0db25e31d]   ESC[1mESC[36mBook Create (0.9ms)ESC[0m  ESC[1mESC[32mINSERT INTO `books` (`googlebooksapi_id`, `title`, `image`, `description`, `created_at`, `updated_at`) VALUES ('-7iMOLUQDqQC', '実践Rails', 'content.jpeg', '本書はRuby on RailsでWebアプリケーションを構築した経験がある人を対象に、Railsの実用テクニックを解説する。Rubyのメタプログラミング機能やRailsの内部構造に始まり、データベースやセキュリティ、パフォーマンス、RESTfulアーキテクチャなどについての実践的なテクニックに至るまでを詳述し、その上で大規模なRailsプロジ
ェクトの管理および他のシステムとのRailsの統合についてを説明する。また、Railsの開発に参加する方法や、Railsを構成するコンポーネントの代替となるソリューション、アプリケーションの国際化などについても扱って
いる。実践的にRailsを使いたいユーザ必携の一冊である。Rails 2.0対応。Rails 2.1プラグイン環境についての記述を付録として収録。', '2020-05-10 13:58:33', '2020-05-10 13:58:33')ESC[0m
D, [2020-05-10T13:58:33.703729 #20106] DEBUG -- : [3438910f-6452-4dd7-9146-6be0db25e31d]   ESC[1mESC[35m (2.9ms)ESC[0m  ESC[1mESC[31mROLLBACKESC[0m
I, [2020-05-10T13:58:33.704631 #20106]  INFO -- : [3438910f-6452-4dd7-9146-6be0db25e31d] Completed 500 Internal Server Error in 748ms (ActiveRecord: 5.2ms)
F, [2020-05-10T13:58:33.705059 #20106] FATAL -- : [3438910f-6452-4dd7-9146-6be0db25e31d]   
F, [2020-05-10T13:58:33.705107 #20106] FATAL -- : [3438910f-6452-4dd7-9146-6be0db25e31d] NoMethodError (undefined method `each' for nil:NilClass):
F, [2020-05-10T13:58:33.705132 #20106] FATAL -- : [3438910f-6452-4dd7-9146-6be0db25e31d]   
F, [2020-05-10T13:58:33.705156 #20106] FATAL -- : [3438910f-6452-4dd7-9146-6be0db25e31d] app/models/google_book.rb:83:in `block in save'
[3438910f-6452-4dd7-9146-6be0db25e31d] app/models/google_book.rb:80:in `save'
[3438910f-6452-4dd7-9146-6be0db25e31d] app/models/google_book.rb:93:in `find_book_or_save'
[3438910f-6452-4dd7-9146-6be0db25e31d] app/controllers/books_controller.rb:8:in `create'

Head First JavaScript

I, [2020-05-10T14:01:19.934587 #20106]  INFO -- : [fefe761e-dce6-452d-bfcc-7ad3141269de] Completed 200 OK in 767ms (Views: 7.6ms | ActiveRecord: 0.0ms)
I, [2020-05-10T14:01:22.176630 #20106]  INFO -- : [5efb0491-0d76-4098-93a8-0c46e48ca799] Started POST "/books?googlebooksapi_id=JxnSxoUdlXEC" for 111.239.252.130 at 2020-05-10 14:01:22 +0000
I, [2020-05-10T14:01:22.177258 #20106]  INFO -- : [5efb0491-0d76-4098-93a8-0c46e48ca799] Processing by BooksController#create as HTML
I, [2020-05-10T14:01:22.177321 #20106]  INFO -- : [5efb0491-0d76-4098-93a8-0c46e48ca799]   Parameters: {"authenticity_token"=>"u2WzhL+pDL7siqUlfxy0IPR28UGQWijX7eGMiJZVWwXCIj3xKjhE8FeEgeoIzwsY3rw75e6soxVewmOtqcn3zA==", "googlebooksapi_id"=>"JxnSxoUdlXEC"}
D, [2020-05-10T14:01:22.823536 #20106] DEBUG -- : [5efb0491-0d76-4098-93a8-0c46e48ca799]   ESC[1mESC[36mBook Load (0.6ms)ESC[0m  ESC[1mESC[34mSELECT  `books`.* FROM `books` WHERE `books`.`googlebooksapi_id` = 'JxnSxoUdlXEC' LIMIT 1ESC[0m
D, [2020-05-10T14:01:22.824932 #20106] DEBUG -- : [5efb0491-0d76-4098-93a8-0c46e48ca799]   ESC[1mESC[36mBook Exists (0.5ms)ESC[0m  ESC[1mESC[34mSELECT  1 AS one FROM `books` WHERE `books`.`googlebooksapi_id` = 'JxnSxoUdlXEC' LIMIT 1ESC[0m
D, [2020-05-10T14:01:22.825522 #20106] DEBUG -- : [5efb0491-0d76-4098-93a8-0c46e48ca799]   ESC[1mESC[35m (0.4ms)ESC[0m  ESC[1mESC[35mBEGINESC[0m
D, [2020-05-10T14:01:23.119061 #20106] DEBUG -- : [5efb0491-0d76-4098-93a8-0c46e48ca799]   ESC[1mESC[36mCACHE Book Exists (0.0ms)ESC[0m  ESC[1mESC[34mSELECT  1 AS one FROM `books` WHERE `books`.`googlebooksapi_id` = 'JxnSxoUdlXEC' LIMIT 1ESC[0m
D, [2020-05-10T14:01:23.122852 #20106] DEBUG -- : [5efb0491-0d76-4098-93a8-0c46e48ca799]   ESC[1mESC[36mBook Create (2.8ms)ESC[0m  ESC[1mESC[32mINSERT INTO `books` (`googlebooksapi_id`, `title`, `image`, `description`, `created_at`, `updated_at`) VALUES ('JxnSxoUdlXEC', 'Head First JavaScript', 'content.jpeg', 'インタラクティブなWebアプリケーションが簡単に作成できる。数多くの図版を使用(しかも思いもよ
らないやり方で)。読者に語りかけるような会話のスタイル。右脳・左脳の活動を活発にさせるように考慮した構成。練習問題で習熟度をチェック。わかりやすく楽しいたとえ。絶対飽きない、挫折しない、類を見ないJavaScriptの入門書。', '2020-05-10 14:01:23', '2020-05-10 14:01:23')ESC[0m
D, [2020-05-10T14:01:23.283935 #20106] DEBUG -- : [5efb0491-0d76-4098-93a8-0c46e48ca799]   ESC[1mESC[35m (2.9ms)ESC[0m  ESC[1mESC[31mROLLBACKESC[0m
I, [2020-05-10T14:01:23.284858 #20106]  INFO -- : [5efb0491-0d76-4098-93a8-0c46e48ca799] Completed 500 Internal Server Error in 1107ms (ActiveRecord: 7.2ms)
F, [2020-05-10T14:01:23.285268 #20106] FATAL -- : [5efb0491-0d76-4098-93a8-0c46e48ca799]   
F, [2020-05-10T14:01:23.285308 #20106] FATAL -- : [5efb0491-0d76-4098-93a8-0c46e48ca799] NoMethodError (undefined method `each' for nil:NilClass):
F, [2020-05-10T14:01:23.285331 #20106] FATAL -- : [5efb0491-0d76-4098-93a8-0c46e48ca799]   
F, [2020-05-10T14:01:23.285357 #20106] FATAL -- : [5efb0491-0d76-4098-93a8-0c46e48ca799] app/models/google_book.rb:83:in `block in save'
[5efb0491-0d76-4098-93a8-0c46e48ca799] app/models/google_book.rb:80:in `save'
[5efb0491-0d76-4098-93a8-0c46e48ca799] app/models/google_book.rb:93:in `find_book_or_save'
[5efb0491-0d76-4098-93a8-0c46e48ca799] app/controllers/books_controller.rb:8:in `create'

**Comment by kumackey** [comment]
Closes by #133
